from datetime import date
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader


def build_payment_ack_pdf(
    payment_id: int,
    amount: float,
    currency: str,
    pay_date: date,
    partner_name: str,
    company_name: str,
    suite_name: str | None = None,
    suite_number: str | None = None,
    schedule_summary: str | None = None,
    have_customer_signature: bool = False,
    have_company_signature: bool = False,
    customer_signature: bytes | None = None,
    company_signature: bytes | None = None,
) -> bytes:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    width, height = A4
    margin = 20 * mm

    # Header
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - margin, "Payment Acknowledgement")

    c.setFont("Helvetica", 10)
    c.drawString(margin, height - margin - 18, company_name)

    # Body
    y = height - margin - 50
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"Payment ID: {payment_id}")
    y -= 18
    c.drawString(margin, y, f"Date: {pay_date.strftime('%Y-%m-%d')}")
    y -= 18
    c.drawString(margin, y, f"Customer: {partner_name}")
    y -= 18
    c.drawString(margin, y, f"Amount: {amount:.2f} {currency}")

    if suite_name:
        y -= 18
        label = suite_name
        if suite_number:
            label = f"{suite_name} ({suite_number})"
        c.drawString(margin, y, f"Suite: {label}")

    if schedule_summary:
        y -= 18
        c.drawString(margin, y, schedule_summary)

    y -= 24
    c.setFont("Helvetica", 11)
    text = (
        "We acknowledge receipt of the payment stated above. This document serves as a confirmation "
        "of funds received for the specified transaction."
    )
    c.drawString(margin, y, text)

    # Signatures (images or notes)
    y = max(y - 30, 90)
    c.setFont("Helvetica", 10)
    sig_height = 20 * mm
    sig_width = 40 * mm
    left_x = margin
    right_x = width - margin - sig_width
    if customer_signature:
        try:
            img = ImageReader(BytesIO(customer_signature))
            c.drawImage(img, left_x, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(left_x, y - 12, "Customer Signature")
        except Exception:
            c.drawString(left_x, y, "Customer Signature: on file")
    elif have_customer_signature:
        c.drawString(left_x, y, "Customer Signature: on file")

    if company_signature:
        try:
            img = ImageReader(BytesIO(company_signature))
            c.drawImage(img, right_x, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(right_x, y - 12, "Company Signature")
        except Exception:
            c.drawString(right_x, y, "Company Signature: on file")
    elif have_company_signature:
        c.drawString(right_x, y, "Company Signature: on file")

    # Footer
    c.setFont("Helvetica", 9)
    c.drawCentredString(width / 2, margin, "Generated by Real Estate Backend")

    # Signatures row
    y = 60 * mm
    sig_height = 20 * mm
    sig_width = 40 * mm
    if customer_signature:
        try:
            img = ImageReader(BytesIO(customer_signature))
            c.drawImage(img, margin, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(margin, y - 12, "Customer Signature")
        except Exception:
            c.drawString(margin, y, "Customer Signature: on file")
    if company_signature:
        try:
            img = ImageReader(BytesIO(company_signature))
            c.drawImage(img, width - margin - sig_width, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(width - margin - sig_width, y - 12, "Company Signature")
        except Exception:
            c.drawString(width - margin - sig_width, y, "Company Signature: on file")

    c.showPage()
    c.save()

    pdf = buffer.getvalue()
    buffer.close()
    return pdf


def _new_canvas():
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    return c, buffer


def build_offer_letter_pdf(
    offer_id: int,
    partner_name: str,
    suite_name: str,
    suite_number: str | None,
    price_total: float,
    validity_date: date | None,
    company_name: str,
    customer_signature: bytes | None = None,
    company_signature: bytes | None = None,
) -> bytes:
    c, buffer = _new_canvas()
    width, height = A4
    margin = 20 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - margin, "Offer Letter")

    y = height - margin - 30
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"Offer ID: {offer_id}")
    y -= 18
    c.drawString(margin, y, f"Customer: {partner_name}")
    y -= 18
    suite_label = suite_name if suite_name else "Suite"
    number = f" {suite_number}" if suite_number else ""
    c.drawString(margin, y, f"Suite: {suite_label}{number}")
    y -= 18
    c.drawString(margin, y, f"Price: {price_total:.2f}")
    y -= 18
    if validity_date:
        c.drawString(margin, y, f"Valid Until: {validity_date.strftime('%Y-%m-%d')}")
        y -= 18

    y -= 12
    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Company: {company_name}")

    # Signatures row
    y = 60 * mm
    sig_height = 20 * mm
    sig_width = 40 * mm
    if customer_signature:
        try:
            img = ImageReader(BytesIO(customer_signature))
            c.drawImage(img, margin, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(margin, y - 12, "Customer Signature")
        except Exception:
            c.drawString(margin, y, "Customer Signature: on file")
    if company_signature:
        try:
            img = ImageReader(BytesIO(company_signature))
            c.drawImage(img, width - margin - sig_width, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(width - margin - sig_width, y - 12, "Company Signature")
        except Exception:
            c.drawString(width - margin - sig_width, y, "Company Signature: on file")

    c.showPage()
    c.save()
    pdf = buffer.getvalue()
    buffer.close()
    return pdf


def build_invoice_pdf(
    invoice_id: int,
    partner_name: str,
    currency: str,
    amount_total: float,
    residual: float | None,
    company_name: str,
    schedule_rows: list[dict] | None = None,
    payments: list[dict] | None = None,
) -> bytes:
    c, buffer = _new_canvas()
    width, height = A4
    margin = 20 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - margin, "Invoice")

    y = height - margin - 30
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"Invoice ID: {invoice_id}")
    y -= 18
    c.drawString(margin, y, f"Customer: {partner_name}")
    y -= 18
    c.drawString(margin, y, f"Amount Total: {amount_total:.2f} {currency}")
    y -= 18
    res = residual or 0.0
    c.drawString(margin, y, f"Residual: {res:.2f} {currency}")

    y -= 24
    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Company: {company_name}")

    if schedule_rows:
        y -= 18
        c.setFont("Helvetica-Bold", 11)
        c.drawString(margin, y, "Payment Schedule:")
        y -= 16
        c.setFont("Helvetica", 10)
        for row in schedule_rows[:20]:
            line = f"{row.get('due_date','')}  Amt: {row.get('amount',0):.2f}  Paid: {row.get('paid_amount',0):.2f}  Outst: {row.get('outstanding_amount',0):.2f}  {row.get('status','')}"
            c.drawString(margin, y, line)
            y -= 14
            if y < 40 * mm:
                break

    if payments:
        y -= 10
        c.setFont("Helvetica-Bold", 11)
        c.drawString(margin, y, "Payments:")
        y -= 16
        c.setFont("Helvetica", 10)
        for p in payments[:25]:
            line = f"{p.get('date','')}: {p.get('amount',0):.2f} {currency}"
            c.drawString(margin, y, line)
            y -= 14
            if y < 30 * mm:
                break

    c.showPage()
    c.save()
    pdf = buffer.getvalue()
    buffer.close()
    return pdf


def build_payment_summary_letter_pdf(
    offer_id: int,
    partner_name: str,
    suite_name: str,
    suite_number: str | None,
    price_total: float,
    total_paid: float,
    balance: float,
    company_name: str,
    schedule_rows: list[dict] | None = None,
    customer_signature: bytes | None = None,
    company_signature: bytes | None = None,
) -> bytes:
    c, buffer = _new_canvas()
    width, height = A4
    margin = 20 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - margin, "Payment Summary Letter")

    y = height - margin - 30
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"Offer ID: {offer_id}")
    y -= 18
    c.drawString(margin, y, f"Customer: {partner_name}")
    y -= 18
    suite_label = suite_name if suite_name else "Suite"
    number = f" {suite_number}" if suite_number else ""
    c.drawString(margin, y, f"Suite: {suite_label}{number}")
    y -= 18
    c.drawString(margin, y, f"Total Price: {price_total:.2f}")
    y -= 18
    c.drawString(margin, y, f"Total Paid: {total_paid:.2f}")
    y -= 18
    c.drawString(margin, y, f"Balance: {balance:.2f}")

    y -= 24
    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Company: {company_name}")

    # Schedule breakdown table (simple)
    if schedule_rows:
        y -= 18
        c.setFont("Helvetica-Bold", 11)
        c.drawString(margin, y, "Schedule Breakdown:")
        y -= 16
        c.setFont("Helvetica", 10)
        for row in schedule_rows[:20]:
            line = f"{row.get('due_date','')}  Amt: {row.get('amount',0):.2f}  Paid: {row.get('paid_amount',0):.2f}  Outst: {row.get('outstanding_amount',0):.2f}  {row.get('status','')}"
            c.drawString(margin, y, line)
            y -= 14
            if y < 40 * mm:
                break

    # Signatures row
    y = 60 * mm
    sig_height = 20 * mm
    sig_width = 40 * mm
    if customer_signature:
        try:
            img = ImageReader(BytesIO(customer_signature))
            c.drawImage(img, margin, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(margin, y - 12, "Customer Signature")
        except Exception:
            c.drawString(margin, y, "Customer Signature: on file")
    if company_signature:
        try:
            img = ImageReader(BytesIO(company_signature))
            c.drawImage(img, width - margin - sig_width, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(width - margin - sig_width, y - 12, "Company Signature")
        except Exception:
            c.drawString(width - margin - sig_width, y, "Company Signature: on file")

    c.showPage()
    c.save()
    pdf = buffer.getvalue()
    buffer.close()
    return pdf


def build_allocation_letter_pdf(
    offer_id: int,
    partner_name: str,
    suite_name: str,
    suite_number: str | None,
    allocation_date: date,
    company_name: str,
    customer_signature: bytes | None = None,
    company_signature: bytes | None = None,
) -> bytes:
    c, buffer = _new_canvas()
    width, height = A4
    margin = 20 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - margin, "Final Letter of Allocation")

    y = height - margin - 30
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"Offer ID: {offer_id}")
    y -= 18
    c.drawString(margin, y, f"Customer: {partner_name}")
    y -= 18
    suite_label = suite_name if suite_name else "Suite"
    number = f" {suite_number}" if suite_number else ""
    c.drawString(margin, y, f"Suite: {suite_label}{number}")
    y -= 18
    c.drawString(margin, y, f"Allocation Date: {allocation_date.strftime('%Y-%m-%d')}")

    y -= 24
    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Company: {company_name}")

    # Signatures row
    y = 60 * mm
    sig_height = 20 * mm
    sig_width = 40 * mm
    if customer_signature:
        try:
            img = ImageReader(BytesIO(customer_signature))
            c.drawImage(img, margin, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(margin, y - 12, "Customer Signature")
        except Exception:
            c.drawString(margin, y, "Customer Signature: on file")
    if company_signature:
        try:
            img = ImageReader(BytesIO(company_signature))
            c.drawImage(img, width - margin - sig_width, y, sig_width, sig_height, preserveAspectRatio=True, mask='auto')
            c.drawString(width - margin - sig_width, y - 12, "Company Signature")
        except Exception:
            c.drawString(width - margin - sig_width, y, "Company Signature: on file")

    c.showPage()
    c.save()
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
